# Generated by Django 5.1.4 on 2025-02-07 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Chem_e_cross',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('college', models.CharField(max_length=100)),
                ('current_year', models.IntegerField()),
                ('state', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('pincode', models.IntegerField(null=True)),
            ],
        ),
    ]
