# Generated by Django 5.1.4 on 2025-02-07 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Azeo_id_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('alternate_phone_number', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=100)),
                ('current_year', models.CharField(choices=[('B.Tech 1st Year', '1st Year B.Tech'), ('B.Tech 2nd Year', '2nd Year B.Tech'), ('B.Tech 3rd Year', '3rd Year B.Tech'), ('B.Tech 4th Year', '4th Year B.Tech'), ('M.Tech 1st Year', '1st Year M.Tech'), ('M.Tech 2nd Year', '2nd Year M.Tech'), ('Ph.D 1st Year', '1st Year Ph.D'), ('Ph.D 2nd Year', '2nd Year Ph.D'), ('Ph.D 3rd Year', '3rd Year Ph.D'), ('Ph.D 4th Year', '4th Year Ph.D')], default='B.Tech 1st Year', max_length=50)),
                ('permanent_address', models.TextField()),
                ('state', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('pincode', models.IntegerField(null=True)),
                ('azeo_id', models.CharField(default=1, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Extendeduser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('alternate_phone_number', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=100)),
                ('current_year', models.CharField(choices=[('B.Tech 1st Year', '1st Year B.Tech'), ('B.Tech 2nd Year', '2nd Year B.Tech'), ('B.Tech 3rd Year', '3rd Year B.Tech'), ('B.Tech 4th Year', '4th Year B.Tech'), ('M.Tech 1st Year', '1st Year M.Tech'), ('M.Tech 2nd Year', '2nd Year M.Tech'), ('Ph.D 1st Year', '1st Year Ph.D'), ('Ph.D 2nd Year', '2nd Year Ph.D'), ('Ph.D 3rd Year', '3rd Year Ph.D'), ('Ph.D 4th Year', '4th Year Ph.D')], default='B.Tech 1st Year', max_length=50)),
                ('permanent_address', models.TextField()),
                ('state', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('pincode', models.IntegerField(null=True)),
            ],
        ),
    ]
