# Generated by Django 5.1.4 on 2025-03-07 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azeoid', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('year_of_study', models.IntegerField()),
                ('azeoid', models.CharField(blank=True, max_length=255)),
                ('college_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='StudentRegistration',
        ),
    ]
