# Generated by Django 5.1.4 on 2025-03-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azeoid', '0002_registration_delete_studentregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='azeoid',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
