# Generated by Django 5.1.4 on 2025-03-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azeoid', '0003_alter_registration_azeoid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='year_of_study',
            field=models.CharField(max_length=200),
        ),
    ]
