# Generated by Django 5.1.4 on 2025-03-07 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azeoid', '0004_alter_registration_year_of_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='year_of_study',
            field=models.CharField(choices=[('BTech', 'BTech'), ('MTech', 'MTech'), ('PhD', 'PhD')], max_length=10),
        ),
    ]
